---
language: ruby
before_install:
  - gem install bundler --version $BUNDLER_VERSION
install: bundle _${BUNDLER_VERSION}_ install
bundler_args: --without development
script: bundle _${BUNDLER_VERSION}_ exec rspec --color --format documentation
notifications:
  email: false
rvm:
  - 2.0.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - TEST_VAGRANT_VERSION=v1.5.4 BUNDLER_VERSION=1.5.3
    - TEST_VAGRANT_VERSION=v1.6.5 BUNDLER_VERSION=1.6.9
    - TEST_VAGRANT_VERSION=v1.7.1 BUNDLER_VERSION=1.7.9
    - TEST_VAGRANT_VERSION=HEAD   BUNDLER_VERSION=1.7.9
